### ISSUE TITLE
Api getDanhMucQuanHe và getDanhMucQuanHeByID đang trùng với Api bên Dân Tộc

### ISSUE THREAD

**Issue by dungnthe150915FPT** [hfngzxje/HumanResourcesManagement#23]
![issues](https://github.com/hfngzxje/HumanResourcesManagement/assets/97139064/55df79a9-e516-4b2f-86be-b534c6754497)

**Comment by vinhtran21** [comment]
getDanhMucDanToc là lấy toàn bộ dân tộc trong db ra, còn getDanhMucDanTocById là lấy ra chi tiết 1 dân tộc. 2 cái khác nhau anh nhé.
